# Generated by Django 5.1.3 on 2024-11-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq_literacy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='literacycard',
            name='image',
        ),
        migrations.AddField(
            model_name='literacycard',
            name='image_url',
            field=models.URLField(default='https://example.com/default-image.jpg'),
            preserve_default=False,
        ),
    ]
