# Generated by Django 5.1.3 on 2024-11-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=255)),
                ('student_full_name', models.CharField(max_length=255)),
                ('picture', models.ImageField(upload_to='card_images/')),
            ],
        ),
        migrations.CreateModel(
            name='GraduateSuccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('linkedin_url', models.URLField()),
            ],
        ),
    ]
