# Generated by Django 5.1.3 on 2024-11-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('success_stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardcontent',
            name='picture',
            field=models.URLField(max_length=500),
        ),
    ]
