# Generated by Django 5.1.3 on 2024-11-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaqAside',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('img_url', models.URLField()),
                ('link_url', models.URLField()),
                ('alt_text', models.CharField(max_length=255)),
            ],
        ),
    ]
