# Generated by Django 5.1.3 on 2024-11-23 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq_research', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researcharticle',
            name='description',
        ),
    ]
